name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write  # needed to create GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distributions
        run: |
          python -m build

      - name: Verify package metadata
        run: |
          twine check dist/*

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  github_release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true

  pypi_publish:
    # This job only runs if you add PYPI_API_TOKEN in repo secrets
    if: ${{ secrets.PYPI_API_TOKEN != '' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
